### PR TITLE
fix(polyvar): when using polyvar's sum in type declarations

### LINKED ISSUE #41: Error on declaration of polyvar's sum
```rescript
type red = [ | #red | #violet ]
type blue = [ | #blue | #violet ]

type color = [
  | red
  | blue
]
```
returns
```
type_declaration [0, 0] - [0, 31]
  type_identifier [0, 5] - [0, 8]
  polyvar_type [0, 11] - [0, 31]
    polyvar_declaration [0, 15] - [0, 19]
      polyvar_identifier [0, 15] - [0, 19]
    polyvar_declaration [0, 22] - [0, 29]
      polyvar_identifier [0, 22] - [0, 29]
type_declaration [1, 0] - [1, 33]
  type_identifier [1, 5] - [1, 9]
  polyvar_type [1, 12] - [1, 33]
    polyvar_declaration [1, 16] - [1, 21]
      polyvar_identifier [1, 16] - [1, 21]
    polyvar_declaration [1, 24] - [1, 31]
      polyvar_identifier [1, 24] - [1, 31]
type_declaration [3, 0] - [10, 1]
  ERROR [3, 7] - [6, 1]
    type_identifier [3, 12] - [3, 17]
    ERROR [4, 2] - [4, 7]
      ERROR [4, 4] - [4, 7]
    ERROR [5, 4] - [5, 8]
```

I unsusccessfully tried to fix it, and I don't have time for now to investigate
more :S

### PR DESCRIPTION
**Pull request by WhyThat**
fix #41

### CODE REVIEW

File: grammar.js [hunk 1]
```diff
@@ -278,10 +278,15 @@ module.exports = grammar({
...
-      $.polyvar_identifier,
-      optional($.polyvar_parameters),
-    )),
+    polyvar_declaration: $ => prec.right(
+      choice(
+        seq(
+          $.polyvar_identifier,
+          optional($.polyvar_parameters),
+        ),
+        $._inline_type
```
Comment (nkrkv) [inline grammar.js:287]:
```suggestion
        $._type_identifier
```

Pretty sure a function type, object type, tuple type make no sense in this case

**Review by nkrkv — CHANGES_REQUESTED** [review]
Thanks! One concern here
