### PR TITLE
fix scanner `and` keyword

### LINKED ISSUE #228: Error: `and` keyword scanner
```rescript
let andd = [1, 2, 3]

andd[0]->Js.log
andd[1]->Js.log
```

[Playground](https://rescript-lang.org/try?version=v10.1.2&code=DYUwLgBAhgdgJnCBeCBtAjAGggJmwZgF0AoY2BVABkIFoA+AKQGcA6YAewHMz44NbGrDpyA)

```
(source_file [0, 0] - [4, 0]
  (ERROR [0, 0] - [3, 15]
    (let_binding [0, 4] - [0, 20]
      pattern: (value_identifier [0, 4] - [0, 8])
      body: (array [0, 11] - [0, 20]
        (number [0, 12] - [0, 13])
        (number [0, 15] - [0, 16])
        (number [0, 18] - [0, 19])))
    (ERROR [2, 3] - [3, 9]
      (value_identifier [2, 3] - [2, 4])
      (array_pattern [2, 4] - [2, 7]
        (number [2, 5] - [2, 6]))
      (module_identifier [2, 9] - [2, 11])
      (ERROR [3, 3] - [3, 4])
      (array_pattern [3, 4] - [3, 7]
        (number [3, 5] - [3, 6])))
    (module_identifier [3, 9] - [3, 11])))
```

### PR DESCRIPTION
**Pull request by aspeddro**
Close #228 

The end of `and` keyword must have a space

```
(source_file [0, 0] - [4, 0]
  (let_declaration [0, 0] - [0, 20]
    (let_binding [0, 4] - [0, 20]
      pattern: (value_identifier [0, 4] - [0, 8])
      body: (array [0, 11] - [0, 20]
        (number [0, 12] - [0, 13])
        (number [0, 15] - [0, 16])
        (number [0, 18] - [0, 19]))))
  (expression_statement [2, 0] - [2, 15]
    (pipe_expression [2, 0] - [2, 15]
      (subscript_expression [2, 0] - [2, 7]
        object: (value_identifier [2, 0] - [2, 4])
        index: (number [2, 5] - [2, 6]))
      (value_identifier_path [2, 9] - [2, 15]
        (module_identifier [2, 9] - [2, 11])
        (value_identifier [2, 12] - [2, 15]))))
  (expression_statement [3, 0] - [3, 15]
    (pipe_expression [3, 0] - [3, 15]
      (subscript_expression [3, 0] - [3, 7]
        object: (value_identifier [3, 0] - [3, 4])
        index: (number [3, 5] - [3, 6]))
      (value_identifier_path [3, 9] - [3, 15]
        (module_identifier [3, 9] - [3, 11])
        (value_identifier [3, 12] - [3, 15])))))
```

### CODE REVIEW

File: src/scanner.c [hunk 1]
```diff
@@ -239,8 +239,11 @@ bool tree_sitter_rescript_external_scanner_scan(
       if (lexer->lookahead == 'n') {
         advance(lexer);
         if (lexer->lookahead == 'd') {
-          // Ignore new lines before `and` keyword (recursive definition)
-          in_multiline_statement = true;
+          advance(lexer);
+          if (is_whitespace(lexer->lookahead)) {
```
Comment (nkrkv) [inline src/scanner.c:243]: I think it should rather check against valid identifier characters (a-z, A-Z, apostrophe, $) rather than whitespace, because `and ` (trailing space) is more or less the same as `and(` (trailing lparen) or `and/*comment*/` (a comment right after). What do you think?

Also, you consume an extra character I’m not sure it won’t break anything. For example, the case with a comment `and/*comment*/`

Would you add some tests?

Also, you consume

Comment (aspeddro) [reply src/scanner.c:243]: > I think it should rather check against valid identifier characters (a-z, A-Z, apostrophe, $) rather than whitespace, because and  (trailing space) is more or less the same as and( (trailing lparen) or and/*comment*/ (a comment right after). What do you think?

I think we should scan for white space as the scanner is after a line break `\n`, so if an `and` following a white space is found then `in_multiline_statement` is true.

Note that `and` is a reserved word, so `and` followed by any character is a syntax error.

A problem found in `main`. The code below is parsed, but it should be an error.

```rescript
let a = 1 andb = 2
```

```
(source_file [0, 0] - [1, 0]
  (let_declaration [0, 0] - [0, 18]
    (let_binding [0, 4] - [0, 9]
      pattern: (value_identifier [0, 4] - [0, 5])
      body: (number [0, 8] - [0, 9]))
    (let_binding [0, 13] - [0, 18]
      pattern: (value_identifier [0, 13] - [0, 14])
      body: (number [0, 17] - [0, 18]))))
```
